export interface ToolEntry {
  name: string
  domain: string
}

// Curated list of AI tools to import.
// Excludes the 31 already-seeded tools.
// Domain is used for website_url, logo URL, and deduplication.
export const TOOL_LIST: ToolEntry[] = [
  // --- Writing & Content ---
  { name: 'Rytr', domain: 'rytr.me' },
  { name: 'Wordtune', domain: 'wordtune.com' },
  { name: 'QuillBot', domain: 'quillbot.com' },
  { name: 'Sudowrite', domain: 'sudowrite.com' },
  { name: 'Anyword', domain: 'anyword.com' },
  { name: 'Peppertype', domain: 'peppertype.ai' },
  { name: 'Hypotenuse AI', domain: 'hypotenuse.ai' },
  { name: 'Scalenut', domain: 'scalenut.com' },
  { name: 'INK Editor', domain: 'inkforall.com' },
  { name: 'Frase', domain: 'frase.io' },
  { name: 'Writer', domain: 'writer.com' },
  { name: 'Longshot AI', domain: 'longshot.ai' },
  { name: 'Cohesive', domain: 'cohesive.so' },
  { name: 'TextCortex', domain: 'textcortex.com' },
  { name: 'Simplified', domain: 'simplified.com' },

  // --- Image Generation & Editing ---
  { name: 'NightCafe', domain: 'nightcafe.studio' },
  { name: 'Playground AI', domain: 'playground.com' },
  { name: 'Ideogram', domain: 'ideogram.ai' },
  { name: 'Adobe Firefly', domain: 'firefly.adobe.com' },
  { name: 'Clipdrop', domain: 'clipdrop.co' },
  { name: 'Photosonic', domain: 'photosonic.writesonic.com' },
  { name: 'Craiyon', domain: 'craiyon.com' },
  { name: 'StarryAI', domain: 'starryai.com' },
  { name: 'DreamStudio', domain: 'dreamstudio.ai' },
  { name: 'Pixlr', domain: 'pixlr.com' },
  { name: 'Remove.bg', domain: 'remove.bg' },
  { name: 'PhotoRoom', domain: 'photoroom.com' },
  { name: 'Lensa', domain: 'prisma-ai.com' },
  { name: 'Artbreeder', domain: 'artbreeder.com' },
  { name: 'Deep Dream Generator', domain: 'deepdreamgenerator.com' },

  // --- Video ---
  { name: 'HeyGen', domain: 'heygen.com' },
  { name: 'Colossyan', domain: 'colossyan.com' },
  { name: 'InVideo', domain: 'invideo.io' },
  { name: 'Fliki', domain: 'fliki.ai' },
  { name: 'Lumen5', domain: 'lumen5.com' },
  { name: 'Opus Clip', domain: 'opus.pro' },
  { name: 'Captions', domain: 'captions.ai' },
  { name: 'Elai', domain: 'elai.io' },
  { name: 'Veed.io', domain: 'veed.io' },
  { name: 'Kapwing', domain: 'kapwing.com' },
  { name: 'Topaz Video AI', domain: 'topazlabs.com' },
  { name: 'Pika', domain: 'pika.art' },
  { name: 'Sora', domain: 'sora.com' },
  { name: 'Kling AI', domain: 'klingai.com' },
  { name: 'Vidnoz', domain: 'vidnoz.com' },

  // --- Audio & Voice ---
  { name: 'Speechify', domain: 'speechify.com' },
  { name: 'Play.ht', domain: 'play.ht' },
  { name: 'Resemble AI', domain: 'resemble.ai' },
  { name: 'Descript Overdub', domain: 'descript.com/overdub' },
  { name: 'Listnr', domain: 'listnr.tech' },
  { name: 'WellSaid Labs', domain: 'wellsaidlabs.com' },
  { name: 'LOVO', domain: 'lovo.ai' },
  { name: 'Podcastle', domain: 'podcastle.ai' },
  { name: 'Krisp', domain: 'krisp.ai' },
  { name: 'AIVA', domain: 'aiva.ai' },
  { name: 'Soundraw', domain: 'soundraw.io' },
  { name: 'Boomy', domain: 'boomy.com' },
  { name: 'Udio', domain: 'udio.com' },
  { name: 'Splash Music', domain: 'splashmusic.com' },

  // --- Coding & Developer Tools ---
  { name: 'Tabnine', domain: 'tabnine.com' },
  { name: 'Amazon CodeWhisperer', domain: 'aws.amazon.com/codewhisperer' },
  { name: 'Sourcegraph Cody', domain: 'sourcegraph.com' },
  { name: 'Pieces', domain: 'pieces.app' },
  { name: 'Codium AI', domain: 'codium.ai' },
  { name: 'AskCodi', domain: 'askcodi.com' },
  { name: 'Blackbox AI', domain: 'blackbox.ai' },
  { name: 'Aider', domain: 'aider.chat' },
  { name: 'Continue', domain: 'continue.dev' },
  { name: 'Devin', domain: 'devin.ai' },
  { name: 'Bolt.new', domain: 'bolt.new' },
  { name: 'v0', domain: 'v0.dev' },
  { name: 'Lovable', domain: 'lovable.dev' },
  { name: 'Windsurf', domain: 'windsurf.com' },

  // --- Productivity & Workspace ---
  { name: 'Taskade', domain: 'taskade.com' },
  { name: 'Clockwise', domain: 'getclockwise.com' },
  { name: 'Reclaim AI', domain: 'reclaim.ai' },
  { name: 'Motion', domain: 'usemotion.com' },
  { name: 'Fireflies.ai', domain: 'fireflies.ai' },
  { name: 'tl;dv', domain: 'tldv.io' },
  { name: 'Supernormal', domain: 'supernormal.com' },
  { name: 'Grain', domain: 'grain.com' },
  { name: 'Fellow', domain: 'fellow.app' },
  { name: 'Cogram', domain: 'cogram.com' },
  { name: 'Miro AI', domain: 'miro.com' },
  { name: 'ClickUp AI', domain: 'clickup.com' },
  { name: 'Tome', domain: 'tome.app' },
  { name: 'Beautiful.ai', domain: 'beautiful.ai' },
  { name: 'Gamma', domain: 'gamma.app' },

  // --- Marketing ---
  { name: 'Surfer SEO', domain: 'surferseo.com' },
  { name: 'MarketMuse', domain: 'marketmuse.com' },
  { name: 'Clearscope', domain: 'clearscope.io' },
  { name: 'Semrush AI', domain: 'semrush.com' },
  { name: 'AdCreative.ai', domain: 'adcreative.ai' },
  { name: 'Predis.ai', domain: 'predis.ai' },
  { name: 'Phrasee', domain: 'phrasee.co' },
  { name: 'Persado', domain: 'persado.com' },
  { name: 'Seventh Sense', domain: 'theseventhsense.com' },
  { name: 'Albert AI', domain: 'albert.ai' },
  { name: 'Pattern89', domain: 'pattern89.com' },
  { name: 'Smartly.io', domain: 'smartly.io' },
  { name: 'Pencil', domain: 'trypencil.com' },
  { name: 'Omneky', domain: 'omneky.com' },

  // --- Sales ---
  { name: 'Gong', domain: 'gong.io' },
  { name: 'Chorus', domain: 'chorus.ai' },
  { name: 'Outreach', domain: 'outreach.io' },
  { name: 'Salesloft', domain: 'salesloft.com' },
  { name: 'Apollo.io', domain: 'apollo.io' },
  { name: 'Lavender', domain: 'lavender.ai' },
  { name: 'Regie.ai', domain: 'regie.ai' },
  { name: 'Clari', domain: 'clari.com' },
  { name: 'People.ai', domain: 'people.ai' },
  { name: 'Seamless.AI', domain: 'seamless.ai' },
  { name: 'Clay', domain: 'clay.com' },
  { name: 'Instantly', domain: 'instantly.ai' },
  { name: 'Lemlist', domain: 'lemlist.com' },

  // --- Customer Support ---
  { name: 'Intercom Fin', domain: 'intercom.com' },
  { name: 'Zendesk AI', domain: 'zendesk.com' },
  { name: 'Freshdesk AI', domain: 'freshdesk.com' },
  { name: 'Ada', domain: 'ada.cx' },
  { name: 'Tidio', domain: 'tidio.com' },
  { name: 'Drift', domain: 'drift.com' },
  { name: 'LivePerson', domain: 'liveperson.com' },
  { name: 'Forethought', domain: 'forethought.ai' },
  { name: 'Cognigy', domain: 'cognigy.com' },
  { name: 'Ultimate', domain: 'ultimate.ai' },
  { name: 'Kustomer', domain: 'kustomer.com' },
  { name: 'Yuma AI', domain: 'yuma.ai' },

  // --- Research & Knowledge ---
  { name: 'Elicit', domain: 'elicit.com' },
  { name: 'Consensus', domain: 'consensus.app' },
  { name: 'Semantic Scholar', domain: 'semanticscholar.org' },
  { name: 'Scite', domain: 'scite.ai' },
  { name: 'Connected Papers', domain: 'connectedpapers.com' },
  { name: 'ChatPDF', domain: 'chatpdf.com' },
  { name: 'Humata', domain: 'humata.ai' },
  { name: 'Genei', domain: 'genei.io' },
  { name: 'Scholarcy', domain: 'scholarcy.com' },
  { name: 'You.com', domain: 'you.com' },
  { name: 'Phind', domain: 'phind.com' },
  { name: 'Kagi', domain: 'kagi.com' },

  // --- Data & Analytics ---
  { name: 'Julius AI', domain: 'julius.ai' },
  { name: 'Obviously AI', domain: 'obviously.ai' },
  { name: 'MonkeyLearn', domain: 'monkeylearn.com' },
  { name: 'Akkio', domain: 'akkio.com' },
  { name: 'MindsDB', domain: 'mindsdb.com' },
  { name: 'Deepnote', domain: 'deepnote.com' },
  { name: 'Hex', domain: 'hex.tech' },
  { name: 'Polymer', domain: 'polymersearch.com' },
  { name: 'Rows', domain: 'rows.com' },
  { name: 'Channel', domain: 'channel.io' },

  // --- Design ---
  { name: 'Framer', domain: 'framer.com' },
  { name: 'Uizard', domain: 'uizard.io' },
  { name: 'Galileo AI', domain: 'usegalileo.ai' },
  { name: 'Khroma', domain: 'khroma.co' },
  { name: 'Fontjoy', domain: 'fontjoy.com' },
  { name: 'Magician for Figma', domain: 'magician.design' },
  { name: 'Diagram', domain: 'diagram.com' },
  { name: 'Vizcom', domain: 'vizcom.ai' },
  { name: 'Krea AI', domain: 'krea.ai' },
  { name: 'Designs.ai', domain: 'designs.ai' },
  { name: 'Brandmark', domain: 'brandmark.io' },
  { name: 'Haikei', domain: 'haikei.app' },

  // --- Social Media ---
  { name: 'Buffer AI', domain: 'buffer.com' },
  { name: 'Hootsuite AI', domain: 'hootsuite.com' },
  { name: 'Sprout Social', domain: 'sproutsocial.com' },
  { name: 'Later', domain: 'later.com' },
  { name: 'Publer', domain: 'publer.io' },
  { name: 'FeedHive', domain: 'feedhive.com' },
  { name: 'Taplio', domain: 'taplio.com' },
  { name: 'Ocoya', domain: 'ocoya.com' },
  { name: 'Postwise', domain: 'postwise.ai' },
  { name: 'Tribescaler', domain: 'tribescaler.com' },
  { name: 'Hypefury', domain: 'hypefury.com' },
  { name: 'Typefully', domain: 'typefully.com' },
  { name: 'Tweet Hunter', domain: 'tweethunter.io' },

  // --- SEO ---
  { name: 'Ahrefs AI', domain: 'ahrefs.com' },
  { name: 'SE Ranking', domain: 'seranking.com' },
  { name: 'Serpstat', domain: 'serpstat.com' },
  { name: 'NeuronWriter', domain: 'neuronwriter.com' },
  { name: 'Dashword', domain: 'dashword.com' },
  { name: 'GrowthBar', domain: 'growthbarseo.com' },
  { name: 'SEO.ai', domain: 'seo.ai' },
  { name: 'Alli AI', domain: 'alliai.com' },
  { name: 'WordLift', domain: 'wordlift.io' },
  { name: 'RankIQ', domain: 'rankiq.com' },

  // --- Automation & No-Code ---
  { name: 'Zapier AI', domain: 'zapier.com' },
  { name: 'Make', domain: 'make.com' },
  { name: 'Bardeen', domain: 'bardeen.ai' },
  { name: 'Activepieces', domain: 'activepieces.com' },
  { name: 'n8n', domain: 'n8n.io' },
  { name: 'Levity', domain: 'levity.ai' },
  { name: 'Axiom', domain: 'axiom.ai' },
  { name: 'Browse AI', domain: 'browse.ai' },
  { name: 'Magical', domain: 'getmagical.com' },
  { name: 'Tray.io', domain: 'tray.io' },

  // --- Chatbots & Assistants ---
  { name: 'Google Gemini', domain: 'gemini.google.com' },
  { name: 'Microsoft Copilot', domain: 'copilot.microsoft.com' },
  { name: 'Character.ai', domain: 'character.ai' },
  { name: 'Pi', domain: 'pi.ai' },
  { name: 'Jasper Chat', domain: 'jasper.ai/chat' },
  { name: 'Chatsonic', domain: 'writesonic.com/chat' },
  { name: 'HuggingChat', domain: 'huggingface.co/chat' },
  { name: 'Mistral AI', domain: 'mistral.ai' },
  { name: 'Cohere', domain: 'cohere.com' },
  { name: 'Together AI', domain: 'together.ai' },
  { name: 'Groq', domain: 'groq.com' },
  { name: 'OpenRouter', domain: 'openrouter.ai' },
  { name: 'Replicate', domain: 'replicate.com' },

  // --- Email ---
  { name: 'Mailchimp AI', domain: 'mailchimp.com' },
  { name: 'Superhuman', domain: 'superhuman.com' },
  { name: 'Flowrite', domain: 'flowrite.com' },
  { name: 'Compose AI', domain: 'compose.ai' },
  { name: 'Smartwriter', domain: 'smartwriter.ai' },
  { name: 'Warmer.ai', domain: 'warmer.ai' },
  { name: 'Mailmeteor', domain: 'mailmeteor.com' },

  // --- Education ---
  { name: 'Khan Academy Khanmigo', domain: 'khanacademy.org' },
  { name: 'Quizlet AI', domain: 'quizlet.com' },
  { name: 'Duolingo Max', domain: 'duolingo.com' },
  { name: 'Photomath', domain: 'photomath.com' },
  { name: 'Socratic', domain: 'socratic.org' },
  { name: 'Coursera AI', domain: 'coursera.org' },
  { name: 'Brainly', domain: 'brainly.com' },

  // --- Legal ---
  { name: 'Harvey AI', domain: 'harvey.ai' },
  { name: 'Casetext', domain: 'casetext.com' },
  { name: 'Spellbook', domain: 'spellbook.legal' },
  { name: 'Legalese Decoder', domain: 'legalesedecoder.com' },
  { name: 'DoNotPay', domain: 'donotpay.com' },

  // --- HR & Recruiting ---
  { name: 'HireVue', domain: 'hirevue.com' },
  { name: 'Textio', domain: 'textio.com' },
  { name: 'Eightfold AI', domain: 'eightfold.ai' },
  { name: 'Beamery', domain: 'beamery.com' },
  { name: 'Paradox', domain: 'paradox.ai' },
  { name: 'Fetcher', domain: 'fetcher.ai' },

  // --- Finance ---
  { name: 'AlphaSense', domain: 'alpha-sense.com' },
  { name: 'Kensho', domain: 'kensho.com' },
  { name: 'Domo AI', domain: 'domo.com' },
  { name: 'Nanonets', domain: 'nanonets.com' },
  { name: 'Vic.ai', domain: 'vic.ai' },
]
