export { resend, FROM_EMAIL, isEmailConfigured } from './client'
export { DealAlertEmail } from './templates/DealAlert'
export { WeeklyDigestEmail } from './templates/WeeklyDigest'
export { VerifyEmail } from './templates/VerifyEmail'
export { sendDealAlertEmail, sendWeeklyDigestEmail, sendVerificationEmail } from './send'
